-- DDL Table CHANNEL (FirebirdSQL 5.0.4)
CREATE TABLE CHANNEL (
    CHANNEL_ID INTEGER NOT NULL PRIMARY KEY,
    CHANNEL_NAME VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,

	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- untuk keperluan apabila item dicreate langsung di module POS

    DATATIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Data awal CHANNEL
INSERT INTO CHANNEL (CHANNEL_ID, CHANNEL_NAME) VALUES (0, 'REGULAR');
INSERT INTO CHANNEL (CHANNEL_ID, CHANNEL_NAME) VALUES (1, 'ONLINE');
