-- DDL Table ITEMSTOCK (FirebirdSQL 5.0.4)
CREATE TABLE ITEMSTOCK (
	STOCKDATE DATE NOT NULL,
    ITEM_ID BIGINT NOT NULL,
	QTY INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT FK_ITEMSTOCK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID) ON DELETE CASCADE,
	CONSTRAINT PK_ITEMSTOCK PRIMARY KEY (STOCKDATE, ITEM_ID)
);

