-- DDL Table PROMOITEM (FirebirdSQL 5.0.4)
CREATE TABLE PROMOITEM (
    PROMOITEM_ID INTEGER NOT NULL PRIMARY KEY,
    PROMOITEM_NAME VARCHAR(150) NOT NULL,
    PROMOITEM_CODE VARCHAR(50),
    PROMOITEM_DESCR VARCHAR(255),
    PROMOITEM_ISACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    PROMOITEM_DATESTART DATE,
    PROMOITEM_DATEEND DATE,
    PROMOITEM_TIMESTART TIME,
    PROMOITEM_TIMEEND TIME,
    PROMOITEM_DATA BLOB SUB_TYPE TEXT
);

-- ==========================================
-- 10 Promo Aktif yang Sudah Expired (Lewat)
-- ==========================================
INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (1, 'Promo Awal Tahun 2025', 'PRM25-NEWYEAR', 'Diskon 10% New Year 2025', TRUE, '2025-01-01', '2025-01-15', '08:00:00', '22:00:00', '{"type":"PERCENT","value":10}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (2, 'Promo Valentine 2025', 'PRM25-VALENTINE', 'Diskon Cokelat & Bunga Valentine', TRUE, '2025-02-10', '2025-02-17', '10:00:00', '21:00:00', '{"type":"PERCENT","value":14}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (3, 'Promo Imlek 2025', 'PRM25-IMLEK', 'Cashback Meriah Angpao Imlek', TRUE, '2025-01-25', '2025-02-05', '09:00:00', '22:00:00', '{"type":"CASHBACK","value":25000}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (4, 'Promo Gajian Maret 2025', 'PRM25-PAYDAY-MAR', 'Promo Payday Maret Hemat', TRUE, '2025-03-25', '2025-04-02', '00:00:00', '23:59:59', '{"type":"PERCENT","value":15}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (5, 'Promo Liburan Sekolah 2025', 'PRM25-SCHOOLHOL', 'Diskon Perlengkapan Sekolah', TRUE, '2025-06-15', '2025-07-15', '08:00:00', '20:00:00', '{"type":"PERCENT","value":20}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (6, 'Promo Kemerdekaan RI 2025', 'PRM25-MERDEKA', 'Promo Diskon Kemerdekaan 17%', TRUE, '2025-08-10', '2025-08-20', '08:00:00', '22:00:00', '{"type":"PERCENT","value":17}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (7, 'Promo Gajian Oktober 2025', 'PRM25-PAYDAY-OCT', 'Payday Gajian Oktober Ceria', TRUE, '2025-10-25', '2025-11-02', '00:00:00', '23:59:59', '{"type":"PERCENT","value":12}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (8, 'Promo Harbolnas 11.11 2025', 'PRM25-HARBOLNAS-11', 'Mega Sale Harbolnas 11.11', TRUE, '2025-11-10', '2025-11-13', '00:00:00', '23:59:59', '{"type":"PERCENT","value":30}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (9, 'Promo Natal 2025', 'PRM25-XMAS', 'Diskon Spesial Hari Raya Natal', TRUE, '2025-12-20', '2025-12-27', '09:00:00', '22:00:00', '{"type":"PERCENT","value":25}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (10, 'Promo Akhir Tahun 2025', 'PRM25-YEAREND', 'Promo Cuci Gudang Akhir Tahun', TRUE, '2025-12-28', '2026-01-05', '08:00:00', '23:59:59', '{"type":"PERCENT","value":40}');


-- ========================================================
-- 20 Promo Aktif dengan Range Date Panjang Sampai 2027
-- ========================================================
INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (11, 'Promo Member Gold 2026-2027', 'PRM-MEMB-GOLD', 'Diskon Flat 10% untuk Member Gold', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":10}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (12, 'Promo Member Platinum 2026-2027', 'PRM-MEMB-PLAT', 'Diskon Flat 15% untuk Member Platinum', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":15}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (13, 'Promo Kategori Sepatu & Apparel', 'PRM-CAT-SHOES', 'Diskon Kategori Sepatu Pilihan', TRUE, '2026-03-01', '2027-12-31', '08:00:00', '22:00:00', '{"type":"PERCENT","value":20}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (14, 'Promo Tas & Aksesoris Elegan', 'PRM-CAT-BAGS', 'Promo Eksklusif Koleksi Tas', TRUE, '2026-04-01', '2027-12-31', '09:00:00', '21:00:00', '{"type":"PERCENT","value":25}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (15, 'Promo Khusus Akhir Pekan', 'PRM-WEEKEND-FLAT', 'Diskon Weekend Ceria Setiap Sabtu-Minggu', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":5}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (16, 'Cashback Pembelian Pertama', 'PRM-FIRST-PURCH', 'Cashback 50k Pengguna Baru', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '23:00:00', '{"type":"CASHBACK","value":50000}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (17, 'Promo Ulang Tahun Outlet', 'PRM-OUTLET-BDAY', 'Promo Ultah Toko Diskon Gede', TRUE, '2026-05-01', '2027-05-31', '10:00:00', '22:00:00', '{"type":"PERCENT","value":30}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (18, 'Promo Kemitraan Komunitas', 'PRM-PARTNER-COMM', 'Diskon Khusus Anggota Komunitas Mitra', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":8}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (19, 'Promo Cuci Gudang Mid-Year', 'PRM-MIDYEAR-SALE', 'Promo Tengah Tahun s.d 2027', TRUE, '2026-06-01', '2027-07-31', '08:00:00', '22:00:00', '{"type":"PERCENT","value":35}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (20, 'Diskon Flat Karyawan', 'PRM-STAFF-DISC', 'Diskon Pembelian Khusus Staff Internal', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":20}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (21, 'Promo Back To School Long-Term', 'PRM-BTS-LONG', 'Promo Back to School Tahunan', TRUE, '2026-07-01', '2027-08-31', '09:00:00', '21:00:00', '{"type":"PERCENT","value":18}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (22, 'Promo Bundling Outerwear', 'PRM-BUND-OUTER', 'Diskon Beli Jaket + Sweater Combo', TRUE, '2026-02-15', '2027-12-31', '08:00:00', '22:00:00', '{"type":"PERCENT","value":22}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (23, 'Promo Clearance Sportswear', 'PRM-CLEAR-SPORT', 'Promo Produk Olahraga Clearance', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":45}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (24, 'Promo Spesial Musim Hujan', 'PRM-SEASON-RAIN', 'Promo Jas Hujan & Payung Kolektif', TRUE, '2026-10-01', '2027-03-31', '08:00:00', '22:00:00', '{"type":"PERCENT","value":15}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (25, 'Promo Malam Minggu Belanja', 'PRM-SATNIGHT-SALE', 'Promo Sabtu Malam Hemat s.d 2027', TRUE, '2026-01-01', '2027-12-31', '18:00:00', '23:59:59', '{"type":"PERCENT","value":12}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (26, 'Promo Belanja Keluarga Hijau', 'PRM-ECO-FRIENDLY', 'Promo Diskon Produk Ramah Lingkungan', TRUE, '2026-01-01', '2027-12-31', '09:00:00', '21:00:00', '{"type":"PERCENT","value":10}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (27, 'Promo Kilat Hari Senin', 'PRM-MONDAY-FLASH', 'Promo Flash Monday Start Awal Minggu', TRUE, '2026-01-01', '2027-12-31', '07:00:00', '12:00:00', '{"type":"PERCENT","value":8}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (28, 'Diskon flat Kartu Kredit Partner', 'PRM-CREDIT-PART', 'Diskon Kerjasama Bank Terpilih', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":15}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (29, 'Promo Akhir Bulan Hemat', 'PRM-MONTEND-SAVING', 'Diskon Spesial Akhir Bulan Selamanya', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"type":"PERCENT","value":11}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (30, 'Promo Hari Anak Nasional', 'PRM-KIDS-DAY', 'Promo Kategori Pakaian Anak', TRUE, '2026-07-20', '2027-07-25', '09:00:00', '20:00:00', '{"type":"PERCENT","value":20}');


-- ==========================================
-- 10 Promo Non-Aktif (ISACTIVE = FALSE)
-- ==========================================
INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (31, 'Promo Opening Store Lama', 'PRM-OLD-OPENING', 'Promo Launching Toko Pertama', FALSE, '2024-01-01', '2024-01-31', '09:00:00', '22:00:00', '{"type":"PERCENT","value":50}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (32, 'Promo Valentine Lama 2024', 'PRM24-VALENTINE', 'Promo Hari Kasih Sayang 2024', FALSE, '2024-02-10', '2024-02-15', '09:00:00', '21:00:00', '{"type":"PERCENT","value":10}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (33, 'Promo Cuci Gudang 2024', 'PRM24-CLEARANCE', 'Clearance Sale Musim Panas 2024', FALSE, '2024-07-01', '2024-07-15', '08:00:00', '22:00:00', '{"type":"PERCENT","value":30}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (34, 'Promo Harbolnas 12.12 2024', 'PRM24-HARBOLNAS-12', 'Mega Sale Akhir Tahun 12.12 2024', FALSE, '2024-12-10', '2024-12-13', '00:00:00', '23:59:59', '{"type":"PERCENT","value":40}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (35, 'Promo Flash Sale Tengah Malam 2024', 'PRM24-MIDNIGHT', 'Midnight Sale 2024', FALSE, '2024-08-01', '2024-08-02', '23:00:00', '03:00:00', '{"type":"PERCENT","value":15}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (36, 'Promo Gajian November 2024', 'PRM24-PAYDAY-NOV', 'Payday Gajian November Hemat', FALSE, '2024-11-25', '2024-12-02', '00:00:00', '23:59:59', '{"type":"PERCENT","value":10}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (37, 'Promo Black Friday 2024', 'PRM24-BLACKFRIDAY', 'Promo Hari Jumat Hitam 2024', FALSE, '2024-11-28', '2024-11-30', '08:00:00', '22:00:00', '{"type":"PERCENT","value":35}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (38, 'Promo Back to School 2024', 'PRM24-BTS', 'Promo Tahun Ajaran Baru 2024', FALSE, '2024-06-15', '2024-07-15', '09:00:00', '20:00:00', '{"type":"PERCENT","value":20}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (39, 'Promo Kemerdekaan RI 2024', 'PRM24-MERDEKA', 'Promo Kemerdekaan RI 79', FALSE, '2024-08-15', '2024-08-18', '08:00:00', '22:00:00', '{"type":"PERCENT","value":17}');

INSERT INTO PROMOITEM (PROMOITEM_ID, PROMOITEM_NAME, PROMOITEM_CODE, PROMOITEM_DESCR, PROMOITEM_ISACTIVE, PROMOITEM_DATESTART, PROMOITEM_DATEEND, PROMOITEM_TIMESTART, PROMOITEM_TIMEEND, PROMOITEM_DATA) 
VALUES (40, 'Promo Hari Buruh 2024', 'PRM24-LABORDAY', 'Diskon Spesial Hari Buruh 2024', FALSE, '2024-05-01', '2024-05-02', '09:00:00', '21:00:00', '{"type":"PERCENT","value":10}');
