-- DDL Table PROMONEXTTX (FirebirdSQL 5.0.4)
CREATE TABLE PROMONEXTTX (
    PROMONEXTTX_ID INTEGER NOT NULL PRIMARY KEY,
    PROMONEXTTX_NAME VARCHAR(150) NOT NULL,
    PROMONEXTTX_CODE VARCHAR(50),
    PROMONEXTTX_DESCR VARCHAR(255),
    PROMONEXTTX_ISACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    PROMONEXTTX_DATESTART DATE,
    PROMONEXTTX_DATEEND DATE,
    PROMONEXTTX_TIMESTART TIME,
    PROMONEXTTX_TIMEEND TIME,
    PROMONEXTTX_DATA BLOB SUB_TYPE TEXT
);

-- =============================================================
-- 5 Promo Next Transaction Aktif yang Sudah Expired (Lewat)
-- =============================================================
INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (1, 'Voucher Next Tx 10k Expired', 'NTX25-10K', 'Voucher belanja 10k untuk transaksi berikutnya', TRUE, '2025-01-01', '2025-06-30', '08:00:00', '22:00:00', '{"value":10000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (2, 'Diskon 10% Next Tx Expired', 'NTX25-10PCT', 'Diskon 10% untuk transaksi berikutnya', TRUE, '2025-02-01', '2025-05-31', '09:00:00', '21:00:00', '{"percent":10}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (3, 'Free Gift Next Tx Expired', 'NTX25-GIFT', 'Hadiah langsung pada transaksi berikutnya', TRUE, '2025-03-01', '2025-08-31', '00:00:00', '23:59:59', '{"gift":"Tumbler"}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (4, 'Voucher Next Tx 25k Expired', 'NTX25-25K', 'Voucher belanja 25k untuk transaksi berikutnya BNI', TRUE, '2025-01-15', '2025-04-15', '08:00:00', '22:00:00', '{"value":25000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (5, 'Diskon 15% Next Tx Expired', 'NTX25-15PCT', 'Diskon 15% transaksi berikutnya minimal 150k', TRUE, '2025-05-01', '2025-07-31', '10:00:00', '22:00:00', '{"percent":15,"min_purchase":150000}');


-- =======================================================================
-- 5 Promo Next Transaction Aktif dengan Range Date Panjang Sampai 2027
-- =======================================================================
INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (6, 'Voucher Belanja 50k Next Tx', 'NTX-50K', 'Voucher belanja 50k untuk transaksi berikutnya s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"value":50000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (7, 'Diskon 15% Next Tx Active', 'NTX-15PCT', 'Diskon 15% untuk transaksi berikutnya s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"percent":15}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (8, 'Free Parking & Gift Voucher', 'NTX-FREE-PARK', 'Gratis parkir & Gift Voucher untuk transaksi berikutnya', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"value":10000,"parking":true}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (9, 'Voucher Cashback 30k Next Tx', 'NTX-CB-30K', 'Voucher Cashback 30k untuk transaksi berikutnya BNI', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"cashback":30000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (10, 'Diskon 20% Next Tx Active', 'NTX-20PCT', 'Diskon 20% transaksi berikutnya minimal 200k', TRUE, '2026-01-01', '2027-12-31', '10:00:00', '22:00:00', '{"percent":20,"min_purchase":200000}');


-- =======================================================================
-- 10 Promo Next Transaction Non-Aktif (ISACTIVE = FALSE)
-- =======================================================================
INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (11, 'Voucher Opening Lama', 'NTX-OLD-OPENING', 'Promo Launching Toko Pertama', FALSE, '2024-01-01', '2024-01-31', '09:00:00', '22:00:00', '{"value":5000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (12, 'Promo Valentine Lama 2024', 'NTX24-VALENTINE', 'Promo Valentine 2024', FALSE, '2024-02-10', '2024-02-15', '09:00:00', '21:00:00', '{"percent":5}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (13, 'Promo Cuci Gudang 2024', 'NTX24-CLEARANCE', 'Clearance Sale Musim Panas 2024', FALSE, '2024-07-01', '2024-07-15', '08:00:00', '22:00:00', '{"percent":15}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (14, 'Promo Harbolnas 12.12 2024', 'NTX24-HARBOLNAS-12', 'Mega Sale Akhir Tahun 12.12 2024', FALSE, '2024-12-10', '2024-12-13', '00:00:00', '23:59:59', '{"value":20000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (15, 'Promo Flash Sale 2024', 'NTX24-MIDNIGHT', 'Midnight Sale 2024', FALSE, '2024-08-01', '2024-08-02', '23:00:00', '03:00:00', '{"percent":10}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (16, 'Promo Gajian November 2024', 'NTX24-PAYDAY-NOV', 'Payday Gajian November Hemat', FALSE, '2024-11-25', '2024-12-02', '00:00:00', '23:59:59', '{"value":5000}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (17, 'Promo Black Friday 2024', 'NTX24-BLACKFRIDAY', 'Promo Hari Jumat Hitam 2024', FALSE, '2024-11-28', '2024-11-30', '08:00:00', '22:00:00', '{"percent":15}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (18, 'Promo Back to School 2024', 'NTX24-BTS', 'Promo Tahun Ajaran Baru 2024', FALSE, '2024-06-15', '2024-07-15', '09:00:00', '20:00:00', '{"percent":10}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (19, 'Promo Kemerdekaan RI 2024', 'NTX24-MERDEKA', 'Promo Kemerdekaan RI 79', FALSE, '2024-08-15', '2024-08-18', '08:00:00', '22:00:00', '{"percent":17}');

INSERT INTO PROMONEXTTX (PROMONEXTTX_ID, PROMONEXTTX_NAME, PROMONEXTTX_CODE, PROMONEXTTX_DESCR, PROMONEXTTX_ISACTIVE, PROMONEXTTX_DATESTART, PROMONEXTTX_DATEEND, PROMONEXTTX_TIMESTART, PROMONEXTTX_TIMEEND, PROMONEXTTX_DATA) 
VALUES (20, 'Promo Hari Buruh 2024', 'NTX24-LABORDAY', 'Diskon Spesial Hari Buruh 2024', FALSE, '2024-05-01', '2024-05-02', '09:00:00', '21:00:00', '{"percent":5}');
