-- DDL Table PROMOPAYM (FirebirdSQL 5.0.4)
CREATE TABLE PROMOPAYM (
    PROMOPAYM_ID INTEGER NOT NULL PRIMARY KEY,
    PROMOPAYM_NAME VARCHAR(150) NOT NULL,
    PROMOPAYM_CODE VARCHAR(50),
    PROMOPAYM_DESCR VARCHAR(255),
    PROMOPAYM_ISACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    PROMOPAYM_DATESTART DATE,
    PROMOPAYM_DATEEND DATE,
    PROMOPAYM_TIMESTART TIME,
    PROMOPAYM_TIMEEND TIME,
    PROMOPAYM_DATA BLOB SUB_TYPE TEXT
);

-- ==========================================================
-- 10 Promo Payment Aktif yang Sudah Expired (Lewat)
-- ==========================================================
INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (1, 'Promo Kartu Kredit BCA Expired', 'PAY25-BCA-CC', 'Diskon 10% dengan CC BCA tahun 2025', TRUE, '2025-01-01', '2025-06-30', '08:00:00', '22:00:00', '{"bank":"BCA","method":"CC","discount_percent":10}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (2, 'Promo Mandiri Debit Expired', 'PAY25-MANDIRI-DB', 'Cashback 20k Debit Mandiri 2025', TRUE, '2025-02-01', '2025-05-31', '09:00:00', '21:00:00', '{"bank":"MANDIRI","method":"DEBIT","cashback":20000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (3, 'Promo QRIS Gopay Expired', 'PAY25-GOPAY-QR', 'Potongan 5k minimal belanja 50k Gopay', TRUE, '2025-03-01', '2025-08-31', '00:00:00', '23:59:59', '{"bank":"GOPAY","method":"QRIS","discount_value":5000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (4, 'Promo CC BNI Expired', 'PAY25-BNI-CC', 'Diskon 15% dengan CC BNI 2025', TRUE, '2025-01-15', '2025-04-15', '08:00:00', '22:00:00', '{"bank":"BNI","method":"CC","discount_percent":15}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (5, 'Promo OVO QRIS Expired', 'PAY25-OVO-QR', 'OVO Cashback 10% maksimal 15k', TRUE, '2025-05-01', '2025-07-31', '10:00:00', '22:00:00', '{"bank":"OVO","method":"QRIS","discount_percent":10,"max_value":15000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (6, 'Promo Bank Mega CC Expired', 'PAY25-MEGA-CC', 'Diskon Spesial 20% Mega CC 2025', TRUE, '2025-07-01', '2025-09-30', '08:00:00', '23:59:59', '{"bank":"MEGA","method":"CC","discount_percent":20}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (7, 'Promo QRIS ShopeePay Expired', 'PAY25-SPAY-QR', 'ShopeePay koin cashback 5%', TRUE, '2025-08-01', '2025-10-31', '09:00:00', '21:00:00', '{"bank":"SHOPEEPAY","method":"QRIS","cashback_percent":5}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (8, 'Promo Kartu Kredit HSBC Expired', 'PAY25-HSBC-CC', 'HSBC CC Diskon 12% Min Belanja 300k', TRUE, '2025-03-15', '2025-09-15', '08:00:00', '22:00:00', '{"bank":"HSBC","method":"CC","discount_percent":12}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (9, 'Promo Bank CIMB Niaga CC Expired', 'PAY25-CIMB-CC', 'CIMB CC Cashback 30k Weekend', TRUE, '2025-06-01', '2025-12-31', '00:00:00', '23:59:59', '{"bank":"CIMB","method":"CC","cashback":30000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (10, 'Promo QRIS Dana Expired', 'PAY25-DANA-QR', 'Dana Potongan flat 15k akhir tahun', TRUE, '2025-11-01', '2025-12-31', '08:00:00', '23:59:59', '{"bank":"DANA","method":"QRIS","discount_value":15000}');


-- ====================================================================
-- 10 Promo Payment Aktif dengan Range Date Panjang Sampai 2027
-- ====================================================================
INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (11, 'Promo Kartu Kredit BCA Active', 'PAY-BCA-CC', 'Diskon 10% CC BCA s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"bank":"BCA","method":"CC","discount_percent":10}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (12, 'Promo Mandiri CC Active', 'PAY-MANDIRI-CC', 'Diskon 15% CC Mandiri s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"bank":"MANDIRI","method":"CC","discount_percent":15}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (13, 'Promo QRIS Gopay Active', 'PAY-GOPAY-QR', 'Potongan 10k Gopay s.d 2027', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"bank":"GOPAY","method":"QRIS","discount_value":10000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (14, 'Promo CC BNI Active', 'PAY-BNI-CC', 'BNI CC Cashback 50k Minimal Belanja 500k', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"bank":"BNI","method":"CC","cashback":50000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (15, 'Promo OVO QRIS Active', 'PAY-OVO-QR', 'OVO Cashback 15% s.d 2027', TRUE, '2026-01-01', '2027-12-31', '10:00:00', '22:00:00', '{"bank":"OVO","method":"QRIS","discount_percent":15,"max_value":20000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (16, 'Promo Bank Mega CC Active', 'PAY-MEGA-CC', 'Diskon Spesial 25% Mega CC s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '23:59:59', '{"bank":"MEGA","method":"CC","discount_percent":25}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (17, 'Promo QRIS ShopeePay Active', 'PAY-SPAY-QR', 'ShopeePay cashback 10% koin', TRUE, '2026-01-01', '2027-12-31', '09:00:00', '21:00:00', '{"bank":"SHOPEEPAY","method":"QRIS","cashback_percent":10}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (18, 'Promo Bank CIMB CC Active', 'PAY-CIMB-CC', 'CIMB CC Diskon 12% flat', TRUE, '2026-01-01', '2027-12-31', '00:00:00', '23:59:59', '{"bank":"CIMB","method":"CC","discount_percent":12}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (19, 'Promo QRIS Dana Active', 'PAY-DANA-QR', 'DANA Potongan 8k s.d 2027', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '23:59:59', '{"bank":"DANA","method":"QRIS","discount_value":8000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (20, 'Promo CC HSBC Active', 'PAY-HSBC-CC', 'HSBC CC Diskon 15% Min Belanja 400k', TRUE, '2026-01-01', '2027-12-31', '08:00:00', '22:00:00', '{"bank":"HSBC","method":"CC","discount_percent":15}');


-- ==========================================================
-- 10 Promo Payment Non-Aktif (ISACTIVE = FALSE)
-- ==========================================================
INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (21, 'Promo LinkAja QRIS Inactive', 'PAY-LINKAJA-QR', 'LinkAja Cashback 10% lama', FALSE, '2024-01-01', '2024-06-30', '09:00:00', '22:00:00', '{"bank":"LINKAJA","method":"QRIS","discount_percent":10}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (22, 'Promo CC Permata Inactive', 'PAY-PERMATA-CC', 'Diskon 5% Permata CC 2024', FALSE, '2024-02-01', '2024-05-31', '09:00:00', '21:00:00', '{"bank":"PERMATA","method":"CC","discount_percent":5}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (23, 'Promo Debit BNI Inactive', 'PAY-BNI-DB', 'Potongan 10k Debit BNI 2024', FALSE, '2024-03-01', '2024-08-31', '08:00:00', '22:00:00', '{"bank":"BNI","method":"DEBIT","discount_value":10000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (24, 'Promo CC Maybank Inactive', 'PAY-MAYBANK-CC', 'Maybank CC Diskon 15%', FALSE, '2024-01-15', '2024-04-15', '08:00:00', '22:00:00', '{"bank":"MAYBANK","method":"CC","discount_percent":15}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (25, 'Promo Sakuku QR Inactive', 'PAY-SAKUKU-QR', 'Sakuku Cashback 10k flat', FALSE, '2024-05-01', '2024-07-31', '10:00:00', '22:00:00', '{"bank":"SAKUKU","method":"QRIS","discount_value":10000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (26, 'Promo CC Danamon Inactive', 'PAY-DANAMON-CC', 'Danamon CC Diskon 20%', FALSE, '2024-07-01', '2024-09-30', '08:00:00', '23:59:59', '{"bank":"DANAMON","method":"CC","discount_percent":20}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (27, 'Promo QRIS Nobu Inactive', 'PAY-NOBU-QR', 'Nobu e-money cashback 5%', FALSE, '2024-08-01', '2024-10-31', '09:00:00', '21:00:00', '{"bank":"NOBU","method":"QRIS","cashback_percent":5}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (28, 'Promo CC Panin Inactive', 'PAY-PANIN-CC', 'Panin CC Diskon 12% Min Belanja 300k', FALSE, '2024-03-15', '2024-09-15', '08:00:00', '22:00:00', '{"bank":"PANIN","method":"CC","discount_percent":12}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (29, 'Promo CC DBS Inactive', 'PAY-DBS-CC', 'DBS CC Cashback 30k Weekend', FALSE, '2024-06-01', '2024-12-31', '00:00:00', '23:59:59', '{"bank":"DBS","method":"CC","cashback":30000}');

INSERT INTO PROMOPAYM (PROMOPAYM_ID, PROMOPAYM_NAME, PROMOPAYM_CODE, PROMOPAYM_DESCR, PROMOPAYM_ISACTIVE, PROMOPAYM_DATESTART, PROMOPAYM_DATEEND, PROMOPAYM_TIMESTART, PROMOPAYM_TIMEEND, PROMOPAYM_DATA) 
VALUES (30, 'Promo QRIS standard Inactive', 'PAY-STD-QR', 'QRIS standard potongan flat 15k', FALSE, '2024-11-01', '2024-12-31', '08:00:00', '23:59:59', '{"bank":"STANDARD","method":"QRIS","discount_value":15000}');
