-- DDL Table SALESPERSON (FirebirdSQL 5.0.4)
CREATE TABLE SALESPERSON (
    SALESPERSON_ID INTEGER NOT NULL,
    SALESPERSON_NIK VARCHAR(20) NOT NULL,
    SALESPERSON_NAME VARCHAR(60) NOT NULL,
    SALESPERSON_ISDISABLED BOOLEAN DEFAULT FALSE NOT NULL,
    BRAND_ID INTEGER,
    SITE_ID INTEGER,
    DATATIMESTAMP TIMESTAMP NOT NULL,
    MD5HASH VARCHAR(32),
    CONSTRAINT PK_SALESPERSON PRIMARY KEY (SALESPERSON_ID),
    CONSTRAINT UQ_SALESPERSON_NIK UNIQUE (SALESPERSON_NIK)
);

-- Index
CREATE INDEX IDX_SALESPERSON_TIMESTAMP ON SALESPERSON (DATATIMESTAMP);
