-- DDL Table SYNCITEM (FirebirdSQL 5.0.4)
CREATE TABLE SYNCITEM (
    SYNCITEM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Waktu sync (sampai menit) waktu local
    SYNCITEM_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- Waktu local, akan diisi 5 hari dari saat insert
    SYNCITEM_CLEARON DATE NOT NULL,
    
    -- Status penyelesaian sync
    SYNCITEM_ISCOMPLETED BOOLEAN DEFAULT FALSE NOT NULL,

    -- Waktu sync (sampai menit) waktu local
    SYNCITEM_COMPLETEDDATE TIMESTAMP,

	SYNCITEM_DURATION INTEGER

);
