-- untuk keperluan melakukan sync bersama secara paralel
-- satu site bisa banyak server
-- untuk menjaga dilakukan bergantian / bergiliran, karena update item yang sama, agar jangan tumpang tindih
CREATE TABLE SYNCITEM (
    SYNCITEM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

)
