-- DDL Table TRX (FirebirdSQL 5.0.4)
CREATE TABLE TRX (
    TRX_ID BIGINT PRIMARY KEY,
    TRX_DOC VARCHAR(50) NOT NULL UNIQUE,
    TRX_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
    TRX_TIME TIME DEFAULT CURRENT_TIME NOT NULL,

	CUSTOMER_ID BIGINT,
    CUSTOMER_DISCOUNT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,   -- subtotal discount (item discount + item promo disc)
	CUSTOMER_NAME VARCHAR(60),
	CUSTOMERTYPE_ID INTEGER,
	CUSTOMER_GENDER INTEGER,
	CUSTOMER_BIRTHDATE DATE,

    QTY INTEGER DEFAULT 0 NOT NULL,

    SUBTOTAL_GROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- subtotal gross (pricegross x qty) 
    SUBTOTAL_DISCOUNT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,   -- subtotal discount (item discount + item promo disc)
    SUBTOTAL_NETT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,   -- subtotal nett (pricenett x qty)
	PROMOPAYM_VALUE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,

    TOTAL DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	TOTAL_FP DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	TOTAL_MD DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,

    TOTAL_PAID DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
    TOTAL_RETURN DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	

	SALES_GROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- jika exclude, nilai gross ini adalah TOTAL + TAX
	TAX_VALUE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	SALES_NETT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,

	DONASI DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	DELIVERY DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	GRANDTOTAL DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,

    CHANNEL_ID INTEGER,
    CASHIER_ID INTEGER,

	SITE_ID INTEGER,
	UNIT_ID INTEGER,
	STRUCT_ID INTEGER,

    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    DATATIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_TRX_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL (CHANNEL_ID),
    CONSTRAINT FK_TRX_CASHIER FOREIGN KEY (CASHIER_ID) REFERENCES USERS (USER_ID)
);

-- Indexing for performance
CREATE INDEX IDX_TRX_NO ON TRX(TRX_NO);
CREATE INDEX IDX_TRX_DATE ON TRX(TRX_DATE);
