-- DDL Table TRX_ITEM (FirebirdSQL 5.0.4)
CREATE TABLE TRX_ITEM (
    TRX_ITEM_ID BIGINT PRIMARY KEY,
    TRX_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,

	BARCODE VARCHAR(50),

 	ITEM_ART VARCHAR(100) NOT NULL,
    ITEM_COL VARCHAR(50),
	ITEM_SIZE VARCHAR(10),
    ITEM_DESCR VARCHAR(255),
	ITEM_PRICEGROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
    ITEM_PRICE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
    ITEM_DISC DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	ITEM_IS_SPECIALPRICE BOOLEAN DEFAULT FALSE NOT NULL,

	ITEM_IS_CONSUMABLE BOOLEAN DEFAULT TRUE NOT NULL,
	ITEM_IS_DONATION BOOLEAN DEFAULT TRUE NOT NULL,
	ITEM_IS_DELIVERY BOOLEAN DEFAULT TRUE NOT NULL,


	PROMOITEM_ID INTEGER,
	PROMOITEM_NOTE VARCHAR(160),  -- +10 add disc 10, 
	                              -- !10 change to 10, 
								  -- ^40 min 40,  --> diambil nilai discount paling besar antar disc item vs disc promo 
								  -- r1000000,    --> rebate 1000000

    QTY INTEGER DEFAULT 1 DEFAULT 0.00 NOT NULL,
    
	PRICEGROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL, -- harga gross
    DISCVALUE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- value total disc dalam rupiah
	PRICENETT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- nilai nett barang setelah discount (sebelum discount payment)
  
    SUBTOTAL_GROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- subtotal gross (pricegross x qty) 
    SUBTOTAL_DISCOUNT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,   -- subtotal discount (item discount + item promo disc)
    SUBTOTAL_NETT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,   -- subtotal nett (pricenett x qty)

	PROMOPAYM_ID INTEGER,	
	PROMOPAYM_NOTE VARCHAR(160),
	PROMOPAYM_VALUE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,

    TOTAL DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	TOTAL_FP DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	TOTAL_MD DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,	

	IS_INCLUDETAX BOOLEAN DEFAULT TRUE NOT NULL,
	SALES_GROSS DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,  -- jika exclude, nilai gross ini adalah TOTAL + TAX
	      											   -- jika include, nilai gross ini sama dengan TOTAL
	TAX_PERCENT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	TAX_VALUE DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	SALES_NETT DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	
	DONASI DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	DELIVERY DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,
	GRANDTOTAL DECIMAL(15, 2) DEFAULT 0.00 NOT NULL,


	CTG_ID INTEGER,
	UNIT_ID INTEGER,
	STRUCT_ID INTEGER,
	BRAND_ID INTEGER,

    DATATIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_TRX_ITEM_TRX FOREIGN KEY (TRX_ID) REFERENCES TRX (TRX_ID)
);

-- Indexing for performance
CREATE INDEX IDX_TRX_ITEM_TRX ON TRX_ITEM(TRX_ID);
