-- DDL Table TRX_PAYM (FirebirdSQL 5.0.4)
CREATE TABLE TRX_PAYM (
    TRX_PAYM_ID BIGINT PRIMARY KEY,
    TRX_ID BIGINT NOT NULL,
	
	PAYMDEV_ID INTEGER,
    PAYMETHOD_ID INTEGER NOT NULL,
    
	PAY_AMOUNT DECIMAL(15, 2) NOT NULL,
	PAY_VALUE DECIMAL(15, 2) NOT NULL,
	PAY_RETURN DECIMAL(15, 2) NOT NULL,
    
	CARD_NO VARCHAR(25),
	CARD_NAME VARCHAR(30),
    APPROVAL_CODE VARCHAR(20),
    
    IS_ADVANCE BOOLEAN DEFAULT TRUE NOT NULL,
	CUSTDEPO_ID BIGINT,
	CUSTDEPO_DOC VARCHAR(50) UNIQUE,
	CUSTDEPO_DESC VARCHAR(100) 

    DATATIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_TRX_PAYM_TRX FOREIGN KEY (TRX_ID) REFERENCES TRX (TRX_ID)
);

-- Indexing for performance
CREATE INDEX IDX_TRX_PAYM_TRX ON TRX_PAYM(TRX_ID);
