-- DDL Table USERS untuk keperluan login (FirebirdSQL 5.0.4)
-- Nama tabel dan kolom disesuaikan dengan UserContract di GEMINI.md

CREATE TABLE USERS (
    USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL, -- Menyimpan hash password (misalnya bcrypt / argon2)
    ROLE VARCHAR(30) NOT NULL,       -- Role pengguna (contoh: 'ADMIN', 'CASHIER')
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Contoh data awal (username: admin, password: password_hash, role: ADMIN)
-- Catatan: password sebaiknya di-hash sebelum dimasukkan ke database.
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) 
VALUES ('admin', '$2a$12$eImiTXuWVxfM37uY4JANj.1Q2e8oDk0wX.HpyXmCgM1k2bM3o4yS2', 'ADMIN');

INSERT INTO USERS (USERNAME, PASSWORD, ROLE) 
VALUES ('agung', '$2a$12$GO8N8p58dfapsuvVjFNRlut0u15zBiEwfbWabzOFWxZYwXGlEttaC', 'ADMIN');
